// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOOUbb2oiCCWKz5bOUng-p3YGaUEDa7ug',
    appId: '1:891462076223:web:a228307639bddd4cd3758a',
    messagingSenderId: '891462076223',
    projectId: 'lmaalem-23777',
    authDomain: 'lmaalem-23777.firebaseapp.com',
    storageBucket: 'lmaalem-23777.firebasestorage.app',
    measurementId: 'G-1KF5SB8NKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7LtlliMMPK7VnlMdu49SOJrv62qfDyeU',
    appId: '1:891462076223:android:3cc2c868adbb1bb4d3758a',
    messagingSenderId: '891462076223',
    projectId: 'lmaalem-23777',
    storageBucket: 'lmaalem-23777.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgMa6k0gYL6Tswlxkd-Pfvx9Senmlh6dY',
    appId: '1:891462076223:ios:6e5f90626422b8a1d3758a',
    messagingSenderId: '891462076223',
    projectId: 'lmaalem-23777',
    storageBucket: 'lmaalem-23777.firebasestorage.app',
    iosBundleId: 'com.example.lmaalem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgMa6k0gYL6Tswlxkd-Pfvx9Senmlh6dY',
    appId: '1:891462076223:ios:6e5f90626422b8a1d3758a',
    messagingSenderId: '891462076223',
    projectId: 'lmaalem-23777',
    storageBucket: 'lmaalem-23777.firebasestorage.app',
    iosBundleId: 'com.example.lmaalem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOOUbb2oiCCWKz5bOUng-p3YGaUEDa7ug',
    appId: '1:891462076223:web:87da161150e1c2c3d3758a',
    messagingSenderId: '891462076223',
    projectId: 'lmaalem-23777',
    authDomain: 'lmaalem-23777.firebaseapp.com',
    storageBucket: 'lmaalem-23777.firebasestorage.app',
    measurementId: 'G-N5B9B0YH8B',
  );

}